version: "3.9"

services:
  representativeness:
    image: representativeness:${TAG-latest}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - .:/app
    ports:
      - 5000:5000
